--- 
after_success: 
  - "npm run coveralls"
before_script: 
  - "psql -c 'create database phantom_test;' -U postgres"
env: 
  - PORT=3000
language: node_js
node_js: 
  - stable
notifications: 
  email: false
script: 
  - "npm ci"
  - "npm run coverage"
services: 
  - postgres