sudo: false

language: node_js

node_js:
  - 'stable'

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE phantom-test;' -U postgres

env:
  - TEST_DATABASE_URL: postgres://localhost:5432/phantom-test
  - PORT: 3000

cache:
  npm: false

notifications:
  email: false

script:
  - npm ci
  - npm run coverage

after_success:
  - npm run coveralls
