sudo: false

language: node_js
node_js:
  - 'stable'
install:
  - npm install

notifications:
  email: false
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database phantom_test;' -U postgres
  - npm run build
script:
  - npm run coverage
after_success:
  - npm run coveralls
